// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbActividades
    {
        public tbActividades()
        {
            tbAgendaDetalles = new HashSet<tbAgendaDetalles>();
        }

        public int acti_Id { get; set; }
        public string acti_Nombre { get; set; }
        public int acti_UsuCreacion { get; set; }
        public DateTime acti_FechaCreacion { get; set; }
        public int? acti_UsuModificacion { get; set; }
        public DateTime? acti_FechaModificacion { get; set; }
        public bool? acti_Estado { get; set; }

        public virtual tbUsuarios acti_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios acti_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbAgendaDetalles> tbAgendaDetalles { get; set; }
    }
}