// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbCategoriaDonaciones
    {
        public tbCategoriaDonaciones()
        {
            tbDonacionesComunes = new HashSet<tbDonacionesComunes>();
        }

        public int cado_Id { get; set; }
        public string cado_NombreCategoria { get; set; }

        public virtual ICollection<tbDonacionesComunes> tbDonacionesComunes { get; set; }
    }
}