// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbCentros
    {
        public tbCentros()
        {
            tbDonacionesXCentro = new HashSet<tbDonacionesXCentro>();
            tbEmpleados = new HashSet<tbEmpleados>();
            tbHabitaciones = new HashSet<tbHabitaciones>();
            tbInventarioPorCentro = new HashSet<tbInventarioPorCentro>();
            tbResidentes = new HashSet<tbResidentes>();
        }

        public int cent_Id { get; set; }
        public string cent_Nombre { get; set; }
        public string muni_Id { get; set; }
        public string cent_Direccion { get; set; }
        public int cent_UsuCreacion { get; set; }
        public DateTime cent_FechaCreacion { get; set; }
        public int? cent_UsuModificacion { get; set; }
        public DateTime? cent_FechaModificacion { get; set; }
        public bool? cent_Estado { get; set; }

        public virtual tbUsuarios cent_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios cent_UsuModificacionNavigation { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual ICollection<tbDonacionesXCentro> tbDonacionesXCentro { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbHabitaciones> tbHabitaciones { get; set; }
        public virtual ICollection<tbInventarioPorCentro> tbInventarioPorCentro { get; set; }
        public virtual ICollection<tbResidentes> tbResidentes { get; set; }
    }
}