// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbDonaciones
    {
        public tbDonaciones()
        {
            tbDonacionesDetalles = new HashSet<tbDonacionesDetalles>();
            tbDonacionesXCentro = new HashSet<tbDonacionesXCentro>();
        }

        public int dona_Id { get; set; }
        public DateTime dona_Fecha { get; set; }
        public int[] cent_Id { get; set; }

        public string dona_QueEs { get; set; }
        public string dona_NombreDonante { get; set; }
        public int dona_UsuCreacion { get; set; }
        public DateTime dona_FechaCreacion { get; set; }
        public int? dona_UsuModificacion { get; set; }
        public DateTime? dona_FechaModificacion { get; set; }
        public bool? dona_Estado { get; set; }

        public virtual tbUsuarios dona_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios dona_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbDonacionesDetalles> tbDonacionesDetalles { get; set; }
        public virtual ICollection<tbDonacionesXCentro> tbDonacionesXCentro { get; set; }
    }
}