// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbDonacionesDetalles
    {
        public int deto_Id { get; set; }
        public int dona_Id { get; set; }
        public int? doco_Id { get; set; }
        public int? deto_Cantidad { get; set; }
        public string deto_Descripcion { get; set; }
        public bool? deto_Estado { get; set; }

        public virtual tbDonacionesComunes doco { get; set; }
        public virtual tbDonaciones dona { get; set; }
    }
}