// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbDonacionesComunes
    {
        public tbDonacionesComunes()
        {
            tbDonacionesDetalles = new HashSet<tbDonacionesDetalles>();
        }

        public int doco_Id { get; set; }
        public string doco_Nombre { get; set; }
        public int cado_Id { get; set; }

        public virtual tbCategoriaDonaciones cado { get; set; }
        public virtual ICollection<tbDonacionesDetalles> tbDonacionesDetalles { get; set; }
    }
}