// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbEnfermedadesXResidente
    {
        public int enferesi_Id { get; set; }
        public int enfe_Id { get; set; }
        public int resi_Id { get; set; }
        public int enferesi_UsuCreacion { get; set; }
        public DateTime enferesi_FechaCreacion { get; set; }
        public int? enferesi_UsuModificacion { get; set; }
        public DateTime? enferesi_FechaModificacion { get; set; }
        public bool? enferesi_Estado { get; set; }

        public virtual tbEnfermedades enfe { get; set; }
        public virtual tbResidentes resi { get; set; }
    }
}