// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbEnfermedades
    {
        public tbEnfermedades()
        {
            tbEnfermedadesXResidente = new HashSet<tbEnfermedadesXResidente>();
        }

        public int enfe_Id { get; set; }
        public string enfe_Nombre { get; set; }
        public int enfe_UsuCreacion { get; set; }
        public DateTime enfe_FechaCreacion { get; set; }
        public int? enfe_UsuModificacion { get; set; }
        public DateTime? enfe_FechaModificacion { get; set; }
        public bool? enfe_Estado { get; set; }

        public virtual tbUsuarios enfe_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios enfe_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEnfermedadesXResidente> tbEnfermedadesXResidente { get; set; }
    }
}