// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbExpedientes
    {
        public int expe_Id { get; set; }
        public int resi_Id { get; set; }
        public int tiposang_Id { get; set; }
        public DateTime expe_FechaApertura { get; set; }
        public string expe_Fotografia { get; set; }
        public string? expe_QRCode { get; set; }
        public int expe_UsuCreacion { get; set; }
        public DateTime expe_FechaCreacion { get; set; }
        public int? expe_UsuModificacion { get; set; }
        public DateTime? expe_FechaModificacion { get; set; }
        public bool? expe_Estado { get; set; }
        public int[] expe_Enfermedades { get; set; }

        public virtual tbUsuarios expe_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios expe_UsuModificacionNavigation { get; set; }
        public virtual tbTiposSangre tiposang { get; set; }
    }
}