// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbHabitaciones
    {
        public tbHabitaciones()
        {
            tbHabitacionesXResidente = new HashSet<tbHabitacionesXResidente>();
        }

        public int habi_Id { get; set; }
        public int habi_Numero { get; set; }
        public int cate_Id { get; set; }
        public int cent_Id { get; set; }
        public int habi_UsuCreacion { get; set; }
        public DateTime habi_FechaCreacion { get; set; }
        public int? habi_UsuModificacion { get; set; }
        public DateTime? habi_FechaModificacion { get; set; }
        public bool? habi_Estado { get; set; }

        public virtual tbCategoriasHabitaciones cate { get; set; }
        public virtual tbCentros cent { get; set; }
        public virtual tbUsuarios habi_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios habi_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbHabitacionesXResidente> tbHabitacionesXResidente { get; set; }
    }
}