// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbHabitacionesXResidente
    {
        public int habiresi_Id { get; set; }
        public int habi_Id { get; set; }
        public int resi_Id { get; set; }
        public int habiresi_UsuCreacion { get; set; }
        public DateTime habiresi_FechaCreacion { get; set; }
        public int? habiresi_UsuModificacion { get; set; }
        public DateTime? habiresi_FechaModificacion { get; set; }
        public bool? habiresi_Estado { get; set; }

        public virtual tbHabitaciones habi { get; set; }
        public virtual tbUsuarios habiresi_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios habiresi_UsuModificacionNavigation { get; set; }
        public virtual tbResidentes resi { get; set; }
    }
}