// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbHistorialExpedientes
    {
        public int histexpe_Id { get; set; }
        public int expe_Id { get; set; }
        public string histexpe_Observaciones { get; set; }
        public int empe_Id { get; set; }
        public DateTime histexpe_FechaActualizacion { get; set; }
        public int histexpe_UsuCreacion { get; set; }
        public DateTime histexpe_FechaCreacion { get; set; }
        public int? histexpe_UsuModificacion { get; set; }
        public DateTime? histexpe_FechaModificacion { get; set; }
        public bool? histexpe_Estado { get; set; }

        public virtual tbEmpleados empe { get; set; }
        public virtual tbUsuarios histexpe_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios histexpe_UsuModificacionNavigation { get; set; }
    }
}