// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbInventarioPorCentro
    {
        public int invecent_Id { get; set; }
        public int medi_Id { get; set; }
        public int cent_Id { get; set; }
        public int invecent_Stock { get; set; }
        public int invecent_UsuCreacion { get; set; }
        public DateTime invecent_FechaCreacion { get; set; }
        public int? invecent_UsuModificacion { get; set; }
        public DateTime? invecent_FechaModificacion { get; set; }
        public bool? invecent_Estado { get; set; }

        public virtual tbCentros cent { get; set; }
        public virtual tbMedicamentos medi { get; set; }
    }
}