// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbMedicamentos
    {
        public tbMedicamentos()
        {
            tbAgendaDetalles = new HashSet<tbAgendaDetalles>();
            tbInventarioPorCentro = new HashSet<tbInventarioPorCentro>();
        }
        public int medi_Id { get; set; }
        public string medi_Nombre { get; set; }
        public int prov_Id { get; set; }
        public int cent_Id { get; set; }
        public int invecent_Stock { get; set; }
        public int medi_UsuCreacion { get; set; }
        public DateTime medi_FechaCreacion { get; set; }
        public int? medi_UsuModificacion { get; set; }
        public DateTime? medi_FechaModificacion { get; set; }
        public bool? medi_Estado { get; set; }

        public virtual tbUsuarios medi_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios medi_UsuModificacionNavigation { get; set; }
        public virtual tbProveedores prov { get; set; }
        public virtual ICollection<tbAgendaDetalles> tbAgendaDetalles { get; set; }
        public virtual ICollection<tbInventarioPorCentro> tbInventarioPorCentro { get; set; }
    }
}