// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class tbParentescos
    {
        public tbParentescos()
        {
            tbEncargados = new HashSet<tbEncargados>();
        }

        public int pare_Id { get; set; }
        public string pare_Nombre { get; set; }
        public int pare_UsuCreacion { get; set; }
        public DateTime pare_FechaCreacion { get; set; }
        public int? pare_UsuModificacion { get; set; }
        public DateTime? pare_FechaModificacion { get; set; }
        public bool? pare_Estado { get; set; }

        public virtual tbUsuarios pare_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios pare_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEncargados> tbEncargados { get; set; }
    }
}