// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class VW_DonacionesaComunes
    {
        public int doco_Id { get; set; }
        public string doco_Nombre { get; set; }
        public int cado_Id { get; set; }
        public string cado_NombreCategoria { get; set; }
    }
}