// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class VW_tbAgendas
    {
        public int agen_Id { get; set; }
        public string agen_Nombre { get; set; }
        public int agen_UsuCreacion { get; set; }
        public string usua_UsuCreacion_Nombre { get; set; }
        public DateTime agen_FechaCreacion { get; set; }
        public int? agen_UsuModificacion { get; set; }
        public string usua_UsuModificacion_Nombre { get; set; }
        public DateTime? agen_FechaModificacion { get; set; }
        public bool agen_Estado { get; set; }
    }
}