// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class VW_tbHistorialExpedientes
    {
        public int histexpe_Id { get; set; }
        public int expe_Id { get; set; }
        public string histexpe_Observaciones { get; set; }
        public int empe_Id { get; set; }
        public string empe_NombreCompleto { get; set; }
        public DateTime histexpe_FechaActualizacion { get; set; }
    }
}