// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class VW_tbProveedores
    {
        public int prov_Id { get; set; }
        public string prov_Nombre { get; set; }
        public string prov_CorreoElectronico { get; set; }
        public string prov_Telefono { get; set; }
        public string muni_Id { get; set; }
        public string muni_Nombre { get; set; }
        public string prov_Direccion { get; set; }
        public int prov_UsuCreacion { get; set; }
        public DateTime prov_FechaCreacion { get; set; }
        public string usua_UsuCreacion_Nombre { get; set; }
        public int? prov_UsuModificacion { get; set; }
        public string usua_UsuModificacion_Nombre { get; set; }
        public DateTime? prov_FechaModificacion { get; set; }
        public bool prov_Estado { get; set; }
    }
}