// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class VW_tbTiposSangre
    {
        public int tiposang_Id { get; set; }
        public string tiposang_Nombre { get; set; }
        public int tiposang_UsuCreacion { get; set; }
        public string usua_UsuCreacion_Nombre { get; set; }
        public DateTime tiposang_FechaCreacion { get; set; }
        public int? tiposang_UsuModificacion { get; set; }
        public string usua_UsuModificacion_Nombre { get; set; }
        public DateTime? tiposang_FechaModificacion { get; set; }
        public bool tiposang_Estado { get; set; }
    }
}