// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class VW_tbCategoriasHabitaciones
    {
        public int cate_Id { get; set; }
        public string cate_Nombre { get; set; }
        public int cate_Capacidad { get; set; }
        public bool cate_Climatizacion { get; set; }
        public int cate_UsuCreacion { get; set; }
        public string usua_UsuCreacion_Nombre { get; set; }
        public DateTime cate_FechaCreacion { get; set; }
        public int? cate_UsuModificacion { get; set; }
        public string usua_UsuModificacion_Nombre { get; set; }
        public DateTime? cate_FechaModificacion { get; set; }
        public bool cate_Estado { get; set; }
    }
}