// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class VW_tbParentescos
    {
        public int pare_Id { get; set; }
        public string pare_Nombre { get; set; }
        public int pare_UsuCreacion { get; set; }
        public string usua_UsuCreacion_Nombre { get; set; }
        public DateTime pare_FechaCreacion { get; set; }
        public int? pare_UsuModificacion { get; set; }
        public string usua_UsuModificacion_Nombre { get; set; }
        public DateTime? pare_FechaModificacion { get; set; }
        public bool pare_Estado { get; set; }
    }
}