// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Asilo.Entities.Entities
{
    public partial class VW_tbActividades
    {
        public int acti_Id { get; set; }
        public string acti_Nombre { get; set; }
        public string acti_Class { get; set; }
        public int acti_UsuCreacion { get; set; }
        public string usua_UsuCreacion_Nombre { get; set; }
        public DateTime acti_FechaCreacion { get; set; }
        public int? acti_UsuModificacion { get; set; }
        public string usua_UsuModificacion_Nombre { get; set; }
        public DateTime? acti_FechaModificacion { get; set; }
        public bool acti_Estado { get; set; }
    }
}